### PR TITLE
Added articles model

### PR DESCRIPTION
**Pull request by christopherwhaas**
Added articles model with relationships, validations and scopes

### CODE REVIEW

**Comment by krishna-donepudi** [comment]
Great job Chris

**Comment by krishna-donepudi** [comment]
I really like the idea of adding articles, but I think it needs more than just the models before I can make a decision. After all, Rails is all about MVC working together, not just the M portion in isolation. If the views and controller are in working order, then I'll pull this into my project.

**Comment by christopherwhaas** [comment]
clench your fists and say (quietly) "Oh shoot, I totally forgot about the views and controller!"

**Comment by christopherwhaas** [comment]
That should do it

**Pull request merged**
